config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "flats#index"
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flat_path(@flat)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @flat = Flat.find(params[:id])
    @flat.destroy
    redirect_to flats_path, status: :see_other
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :description, :address, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<%= render 'layouts/banner' %>

<div class="container" >
  <div class="row">
      <% @flats.each do |flat| %>
        <div class="card-flat center-block col-5 m-4">
        <h2> <%= flat.name %> </h2>
        <p> <%= flat.description %> </p>
        <div class="address"> <%= flat.address %> </div>
        <div class="price"><%= flat.price_per_night %> euros per night </div>
        <div class="people"><%= flat.number_of_guests %> guests </div>
        <div class="btn">
        <%= link_to "See details", flat_path(flat)%>
  </div>
        </div>
      <% end %>
    </div>
  </div>

  <div class="btn">
    <%= link_to "Create a new flat", new_flat_path%>
  </div>
</div>

app/views/flats/show.html.erb
<div class="container">
  <h1><%= @flat.name %></h1>


  <div class="btn">
    <%= link_to "All flats", flats_path%>
  </div>

</div>

app/views/layouts/_banner.html.erb
<div class="banner" style="background-image: #907F9F; background-size: cover;">
  <div class="container">
    <h1>Find the flat of your dream</h1>
    <p>Change your life and rent a flat.</p>
    <a class="btn btn-flat" href="#">Look for it now</a>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">

  </head>

  <body>
    <%= yield %>
  </body>
</html>